import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
    <html lang="fr">
      <body className={`${inter.variable} font-sans antialiased`}>
>>>>>>> f9aae73 (Refonte visuelle complète : palette indigo/slate + police Inter)
        {children}
      </body>
    </html>
  );
}
